// <auto-generated />
namespace PDKS_Code_First.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class cocuktabloguncelleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cocuktabloguncelleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202301211012085_cocuktabloguncelleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
